---
# Common variables for all systems

dotfiles_user: "{{ ansible_facts['user_id'] }}"
dotfiles_home: "{{ ansible_facts['env']['HOME'] }}"
dotfiles_dir: "{{ playbook_dir }}"
config_dir: "{{ dotfiles_home }}/.config"

# Shared keyboard repeat policy (milliseconds).
keyboard_repeat_interval_ms: 20
keyboard_initial_repeat_delay_ms: 150

# Path to Brewfile
brewfile_path: "{{ dotfiles_dir }}/Brewfile"

# Path to configs for stow
configs_path: "{{ dotfiles_dir }}"
