---
# Linux specific variables

homebrew_prefix: /home/linuxbrew/.linuxbrew
homebrew_bin: "{{ homebrew_prefix }}/bin"

# System packages to install before Homebrew
linux_system_packages_debian:
  - build-essential
  - curl
  - file
  - git
  - jq
  - procps
  - zsh
  - stow
  - unzip
  - xkbset
  - x11-xserver-utils

linux_system_packages_redhat:
  - "@Development Tools"
  - curl
  - file
  - git
  - jq
  - procps-ng
  - zsh
  - stow
  - unzip
  - xkbset
  - xset
