source $(brew --prefix)/opt/spaceship/spaceship.zsh

# Prompt order
SPACESHIP_PROMPT_ORDER=(
time 
user 
dir 
host 
git 
node 
docker 
kubectl 
exec_time 
line_sep 
battery 
jobs 
exit_code 
char 
)

# Character
SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_COLOR_SUCCESS="green"
SPACESHIP_CHAR_COLOR_FAILURE="red"

# Time
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_COLOR="yellow"
SPACESHIP_TIME_FORMAT="%D{%H:%M:%S}"

# User
SPACESHIP_USER_SHOW=always
SPACESHIP_USER_COLOR="blue"
SPACESHIP_USER_COLOR_ROOT="red"

# Host
SPACESHIP_HOST_SHOW=always
SPACESHIP_HOST_COLOR="cyan"

# Directory
SPACESHIP_DIR_COLOR="yellow"
SPACESHIP_DIR_TRUNC=3
SPACESHIP_DIR_TRUNC_REPO=false

# Git
SPACESHIP_GIT_BRANCH_COLOR="magenta"
SPACESHIP_GIT_STATUS_COLOR="red"

# Languages
SPACESHIP_NODE_COLOR="green"
SPACESHIP_DOCKER_COLOR="blue"
SPACESHIP_KUBECTL_COLOR="cyan"

# Exit code
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_COLOR="red"

# Battery
SPACESHIP_BATTERY_SHOW=always
SPACESHIP_BATTERY_THRESHOLD=30
