---
# Node role defaults

node_nvm_version: "v0.40.6"
node_npm_global_packages:
  - name: "@beads/bd"
    version: "1.1.2"
  - name: "@gastown/gt"
    version: "0.12.0"
  - name: nx
    version: "23.1.1"
  - name: "@nestjs/cli"
    version: "11.0.24"
  - name: "@angular/cli"
    version: "22.1.2"
  - name: repomix
    version: "1.17.0"
