# ============================================
# BASE CONFIGURATION
# ============================================
source-file ~/.config/tmux/tmux.theme.conf
source-file ~/.config/tmux/tmux.binds.conf
source-file ~/.config/tmux/tmux.options.conf
source-file ~/.config/tmux/tmux.plugins.conf

set-option -g default-terminal 'tmux-256color'
set-option -as terminal-features ',xterm-ghostty:RGB'

# ============================================
# TPM INITIALIZATION
# ============================================
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins'
if-shell -b 'test -x ~/.config/tmux/plugins/tpm/tpm' \
  'run-shell ~/.config/tmux/plugins/tpm/tpm'
